##===- tools/COTPasses/Makefile ----------------------------*- Makefile -*-===##

LEVEL = ../..

LIBRARYNAME = COTPasses

LOADABLE_MODULE = 1

USEDLIBS = cotInstructionCount.a cotHelloLLVM.a cotFunctionEraser.a cotModuloScheduling.a

include $(LEVEL)/Makefile.common
